# Generated by Django 3.1.1 on 2021-01-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compliments',
            new_name='Complements',
        ),
    ]
