# Generated by Django 3.1.1 on 2021-01-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_auto_20210104_1137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complements',
            new_name='Complement',
        ),
        migrations.RenameModel(
            old_name='Menus',
            new_name='Menu',
        ),
        migrations.RenameModel(
            old_name='RecipeItems',
            new_name='RecipeItem',
        ),
    ]
