# Generated by Django 3.1.1 on 2021-01-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_auto_20210104_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitem',
            name='cook_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='directions',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='ingredients',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='prep_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='servings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
