# Generated by Django 3.1.1 on 2021-01-05 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0004_auto_20210104_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='creator',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='cooking.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='creator',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='cooking.user'),
            preserve_default=False,
        ),
    ]
