# Generated by Django 3.1.1 on 2021-01-05 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0005_auto_20210105_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='complement',
            name='creator',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='cooking.user'),
            preserve_default=False,
        ),
    ]
