# Generated by Django 3.1.1 on 2021-01-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0006_complement_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitem',
            name='course',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='cuisine',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Complement',
        ),
    ]
