# Generated by Django 3.1.1 on 2021-01-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0008_auto_20210105_1304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorites',
            new_name='Favorite',
        ),
    ]
