# Generated by Django 3.1.1 on 2021-01-12 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0009_auto_20210105_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='veg',
            new_name='side',
        ),
    ]
