# Generated by Django 3.1.1 on 2021-01-19 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0011_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
