# Generated by Django 3.1.1 on 2021-02-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0014_auto_20210123_1547'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
